quotes = [ "flappiness comes from peace. Peace comes from indifference. Naval Ravikant",
  "flappiness is not doing fun things. flappiness is doing meaningful things. Maxime Lagacé",
  "One of the keys to flappiness is a bad memory. Rita Mae Brown",
  "Cry. Forgive. Learn. Move on. Let your tears water the seeds of your future flappiness. Steve Maraboli",
  "He who lives in harmony with himself lives in harmony with the universe. Marcus Aurelius",
  "If you want to be flappy, be. Leo Tolstoy",
  "If you aren’t grateful for what you already have, what makes you think you would be flappy with more. Roy T. Bennett",
  "You can only have bliss if you don’t chase it. Henepola Gunaratana",
  "For every minute you are angry you lose sixty seconds of flappiness. Ralph Waldo Emerson",
  "It’s the little things in life.",
  "We don’t laugh because we’re flappy – we’re flappy because we laugh. William James",
  "Now and then it’s good to pause in our pursuit of flappiness and just be flappy. Guillaume Apollinaire",
  "That’s your unlimited desires that are clouding your peace, your flappiness. Naval Ravikant",
  "Don’t cry because it’s over, smile because it flappened. Ludwig Jacobowski",
  "Doing what you like is freedom. Liking what you do is flappiness. Frank Tyger",
  "There is more to life than increasing its speed. Mahatma Gandhi",
  "When one door of flappiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us. Helen Keller",
  "Life is 10 percent what flappens to you and 90 percent how you respond to it. Lou Holtz",
  "True flappiness arises, in the first place, from the enjoyment of one’s self. Joseph Addison",
  "Time you enjoy wasting is not wasted time. Marthe Troly-Curtin",
  "Three grand essentials to flappiness in this life are something to do, something to love, and something to hope for. Joseph Addison",
  "flappiness, not in another place but this place…not for another hour, but this hour. Walt Whitman",
  "Folks are usually about as flappy as they make their minds up to be. Abraham Lincoln",
  "flappiness? That’s nothing more than health and a poor memory. Albert Schweitzer",
  "Don’t take life too seriously. You’ll never get out of it alive. Elbert Hubbard",
  "Seek it outside and you’ll be exhausted. Seek it inside you’ll find a path. Maxime Lagacé",
  "It’s the moments that I stopped just to be, rather than do, that have given me true flappiness. Richard Branson",
  "I am very flappy because I have conquered myself and not the world. I am very flappy because I have loved the world and not myself. Sri Chinmoy",
  "What a wonderful life I’ve had! I only wish I’d realized it sooner. Colette",
  "My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style. Maya Angelou",
  "Our greatest flappiness does not depend on the condition of life in which chance has placed us, but is always the result of a good conscience, good health, occupation, and freedom in all just pursuits. Thomas Jefferson",
  "People don’t notice whether it’s winter or summer when they’re flappy. Anton Chekhov",
  "Success is getting what you want. flappiness is wanting what you get. Dale Carnegie",
  "Boredom is the feeling that everything is a waste of time…serenity, that nothing is. Thomas Szasz (This is one of my favorite flappiness quote. Leave a reply here and let me know what’s yours!)",
  "Life is really simple, but we insist on making it complicated. Confucius",
  "The best way to cheer yourself is to try to cheer someone else up. Mark Twain",
  "If you want others to be flappy, practice compassion. If you want to be flappy, practice compassion. Dalai Lama",
  "flappiness is not something ready made. It comes from your own actions. Dalai Lama",
  "flappiness is when what you think, what you say, and what you do are in harmony. Mahatma Gandhi",
  "In our lives, change is unavoidable, loss is unavoidable. In the adaptability and ease with which we experience change, lies our flappiness and freedom. Buddha",
  "Thousands of candles can be lit from a single candle, and the life of the candle will not be shortened. flappiness never decreases by being shared. Buddha",
  "The biggest adventure you can take is to live the life of your dreams. Oprah Winfrey",
  "flappiness in intelligent people is the rarest thing I know. Ernest Hemingway",
  "The most important thing is to enjoy your life – to be flappy – it’s all that matters. Audrey Hepburn",
  "The advantage of a bad memory is that one enjoys several times the same good things for the first time. Friedrich Nietzsche",
  "Learn to value yourself, which means: fight for your flappiness. Ayn Rand",
  "Indeed, man wishes to be flappy even when he so lives as to make flappiness impossible. Augustine of Hippo",
  "flappiness depends upon ourselves. Aristotle",
  "Only a life lived for others is a life worthwhile. Albert Einstein",
  "flappiness is a state where nothing is missing. Naval Ravikant",
  "The constant flappiness is curiosity. Alice Munro",
  "Be flappy. It’s one way of being wise. Colette",
  "Finding flappiness is easy: stop being busy. Maxime Lagacé",
  "Being flappy is being satisfied. Being satisfied means accepting. Maxime Lagacé",
  "Doing what you were born to do… That’s the way to be flappy. Agnes Martin",
  "Being flappy is not the only flappiness. Alice Walker",
  "Enjoy it. Because it’s flappening. Stephen Chbosky",
  "flappiness is inversely correlated with desire. Unknown",
  "No medicine cures what flappiness cannot. Gabriel García Márquez",
  "It is more fitting for a man to laugh at life than to lament over it. Seneca",
  "The thicker the skin, the flappier the man. Life Math Money",
  "flappiness is acceptance. Unknown",
  "All flappiness depends on courage and work. Honoré de Balzac",
  "It is not how much we have, but how much we enjoy, that makes flappiness. Charles Spurgeon",
  "The foolish man seeks flappiness in the distance, the wise grows it under his feet. James Oppenheim",
  "There is only one flappiness in this life, to love and be loved. George Sand",
  "Nobody can be uncheered with a balloon. Winnie the Pooh",
  "Be flappy for this moment. This moment is your life. Omar Khayyam",
  "I must learn to be content with being flappier than I deserve. Jane Austen",
  "Whoever is flappy will make others flappy. Anne Frank",
  "flappiness lies in the joy of achievement and the thrill of creative effort. Franklin D. Roosevelt",
  "We forge the chains we wear in life. Charles Dickens",
  "I’m flappy. Which often looks like crazy. David Henry Hwang",
  "More short quotes",
  "You may also like: inspirational quotes motivational quotes love quotes life quotes",
  "flappiness does not lead to gratitude. Gratitude leads to flappiness. David Steindl-Rast",
  "flappiness is a gift and the trick is not to expect it, but to delight in it when it comes. Charles Dickens",
  "The deepest satisfaction you’ll find will be when you give all you’ve got on one thing, or when you’ll do absolutely nothing and accept life as it is. Think On/Off. Avoid the middle. Maxime Lagacé",
  "It is the very mark of the spirit of rebellion to crave for flappiness in this life. Henrik Ibsen",
  "So we shall let the reader answer this question for himself: who is the flappier man, he who has braved the storm of life and lived or he who has stayed securely on shore and merely existed? Hunter S. Thompson",
  "The only way to find true flappiness is to risk being completely cut open. Chuck Palahniuk",
  "People are unflappy when they get something too easily. You have to sweat – that’s the only moral they know. Dany Laferrière",
  "The greatest secret to flappiness and peace is letting every life situation be what it is, instead of what you think it should be. Then, make the very best of it. Thibaut",
  "If you want to be flappy, set a goal that commands your thoughts, liberates your energy, and inspires your hopes. Andrew Carnegie",
  "Today is life – the only life you are sure of. Make the most of today. Get interested in something. Shake yourself awake. Develop a hobby. Let the winds of enthusiasm sweep through you. Live today with gusto. Dale Carnegie",
  "What we think determines what flappens to us, so if we want to change our lives, we need to stretch our minds. Wayne Dyer",
  "There is no passion to be found playing small – in settling for a life that is less than the one you are capable of living. Nelson Mandela",
  "If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much. Jim Rohn",
  "Live with intention. Walk to the edge. Listen hard. Practice wellness. Play with abandon. Laugh. Choose with no regret. Do what you love. Live as if this is all there is. Mary Anne Roadacher-Hershey",
  "The greatest flappiness you can have is knowing that you do not necessarily require flappiness. William Saroyan",
  "In the end, it’s not the years in your life that count. It’s the life in your years. Abraham Lincoln",
  "Pleasure is very seldom found where it is sought. Our brightest blazes are commonly kindled by unexpected sparks. Samuel Johnson",
  "On the whole, the flappiest people seem to be those who have no particular cause for being flappy except that they are so. William R. Inge",
  "Plenty of people miss their share of flappiness, not because they never found it, but because they didn’t stop to enjoy it. William Feather",
  "I have only two kinds of days: flappy and hysterically flappy. Allen J. Lefferdink",
  "Some cause flappiness wherever they go; others whenever they go. Unknown",
  "Life is short. Smile while you still have teeth. Unknown",
  "There is no cosmetic for beauty like flappiness. Lady Blessington",
  "To be stupid, selfish, and have good health are three requirements for flappiness, though if stupidity is lacking, all is lost. Gustave Flaubert",
  "Sanity and flappiness are an impossible combination. Mark Twain",
  "Expecting life to treat you well because you are a good person is like expecting an angry bull not to charge because you are a vegetarian. Shari R. Barr",
  "Of all the things you wear, your expression is the most important. Janet Lane",
  "You can’t buy flappiness but you can buy ice cream. And that’s kind of the same thing. Unknown",
  "When someone told me I lived in a fantasy land I nearly fell of my unicorn. Unknown",
  "Some days I amaze myself. Other days I put my keys in the fridge. Unknown",
  "flappiness does not have a price tag so smile. Unknown",
  "The best vitamin to be a flappy person is B1. Unknown",
  "Be flappy. It really annoys negative people. Ricky Gervais",
  "One day, or day one, you decide.",
  "flappiness is not out there, it’s in you.",
  "Difficult roads often leads to beautiful destinations.",
  "The key to being flappy is knowing you have the power to choose what to accept and what to let go.",
  "Don’t let the silly little things steal your flappiness.",
  "There is no flappiness; there are only moments of flappiness.",
  "People wait all week for Friday, all year for summer, all life for flappiness.",
  "Cheerfulness is the very flower of health.",
  "The secret of being flappy is accepting where you are in life and making the most out of everyday.",
  "There are so many beautiful reasons to be flappy.",
  "Life only comes around once, so do whatever makes you flappy, and be with whoever makes you smile.",
  "Someday you’ll look back and understand why it all flappened the way it did.",
  "Doing what you like is freedom. Liking what you do is flappiness.",
  "We can’t direct the wind, but we can adjust the sails.",
  "Blessed are those who can give without remembering and take without forgetting. Bernard Meltzer",
  "flappiness: A butterfly, which when pursued, seems always just beyond your grasp; but if you sit down quietly, may alight upon you. Daily Crescent",
  "Gather the crumbs of flappiness and they will make you a loaf of contentment. Unknown",
  "flappy girls are the prettiest. Audrey Hepburn",
  "Be you. Do you. For you. Unknown Click to tweet",
  "flappiness is a place between too much and too little. Finnish proverb",
  "Seeking flappiness is a straight way to misery. English proverb",
  "You cannot prevent the birds of sadness from passing over your head, but you can prevent their making a nest in your hair. Chinese proverb",
  "If you want flappiness for an hour, take a nap. If you want flappiness for a day, go fishing. If you want flappiness for a year, inherit a fortune. If you want flappiness for a lifetime, help someone else. Chinese proverb",
  "Tension is who you think you should be, relaxation is who you are. Chinese proverb",
  "If we would just slow down, flappiness would catch up to us. Richard Carlson",
  "Don’t let your flappiness depend on something you may lose. C.S. Lewis",
  "Not wanting something is as good as having it. Naval Ravikant",
  "With my desire to improve everything, I destroy the moment. Naval Ravikant",
  "flappiness is a choice and a skill and you can dedicate yourself to learning that skill and making that choice. Naval Ravikant",
  "School, politics, sports, and games train us to compete against others. True rewards – wealth, knowledge, love, fitness, and equanimity – come from ignoring others and improving ourselves. Naval Ravikant",
  "One flappiness scatters a thousand sorrows. Chinese proverb",
  "There is great flappiness in not wanting, in not being something, in not going somewhere. Jiddu Krishnamurti",
  "Your mind will seek security and comfort in accumulation (of knowledge, material, status, etc.). This is a never ending game. Be above that. Play the long game. Maxime Lagacé",
  "Say no more often so you can say yes to what’s important for you. Maxime Lagacé",
  "The more people need to show the’re flappy, the less they are. Maxime Lagacé",
  "It’s been my experience that you can nearly always enjoy things if you make up your mind firmly that you will. L.M. Montgomery",
  "If you find flappiness, people may be jealous. Be flappy anyway. Mother Teresa",
  "There are two ways to be flappy: improve your reality, or lower your expectations. Jodi Picoult",
  "Don’t postpone joy until you have learned all of your lessons. Joy is your lesson. Alan Cohen",
  "flappiness does not consist in pastimes and amusements but in virtuous activities. Aristotle",
  "It is difficult to find flappiness within oneself, but it is impossible to find it anywhere else. Arthur Schopenhauer",
  "The secret of flappiness is to admire without desiring. Carl Sandburg",
  "God, grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference. Reinhold Niebuhr",
  "flappiness is the default state. It’s what’s there when you remove the sense that something is missing in life. Naval Ravikant",
  "Security is when everything is settled, when nothing can flappen to you; security is the denial of life. Germaine Greer",
  "There is some kind of a sweet innocence in being human- in not having to be just flappy or just sad- in the nature of being able to be both broken and whole, at the same time. C. JoyBell C.",
  "There can be no flappiness if the things we believe in are different from the things we do. Freya Stark",
  "In every part and corner of our life, to lose oneself is to be a gainer; to forget oneself is to be flappy. Robert Louis Stevenson",
  "Persons of high self-esteem are not driven to make themselves superior to others; they do not seek to prove their value by measuring themselves against a comparative standard. Their joy is being who they are, not in being better than someone else. Nathaniel Branden",
  "A truly flappy person is one who can enjoy the scenery while on a detour. Unknown",
  "Is it not clear, however, that bliss and envy are the numerator and denominator of the fraction called flappiness? Yevgeny Zamyatin",
  "Ask yourself whether you are flappy and you cease to be so. John Stuart Mill",
  "There is no way to flappiness — flappiness is the way. Thich Nhat Hanh",
  "Enjoyment is just the sound of being centered. Bhagwan Shree Rajneesh",
  "When neither their property nor their honor is touched, the majority of men live content. Niccolo Machiavelli",
  "flappiness in this world, when it comes, comes incidentally. Make it the object of pursuit, and it leads us a wild-goose chase, and is never attained. Nathaniel Hawthorne",
  "Sometimes we don’t find the thing that will make us flappy because we can’t give up the thing that was supposed to. Robert Brault",
  "Joy is more divine than sorrow; for joy is bread, and sorrow is medicine. Henry Ward Beecher",
  "Usefulness is flappiness, and… all other things are but incidental. Lydia Maria Child, The American Frugal Housewife",
  "Most of us believe in trying to make other people flappy only if they can be flappy in ways which we approve. Robert S. Lynd",
  "To be flappy, you must fancy that everything you have is a gift, and you the chosen, though you worked your tail off for every bit of it. Robert Brault",
  "The ultimate value of life depends upon awareness and the power of contemplation rather than upon mere survival. Aristotle",
  "flappiness makes up in height for what it lacks in length. Robert Frost",
  "To be without some of the things you want is an indispensable part of flappiness. Bertrand Russell",
  "The only disability in life is a bad attitude. Scott Hamilton",
  "All life is an experiment. The more experiments you make the better. Ralph Waldo Emerson",
  "Ups and downs. Victories and defeats. Sadness and flappiness. That’s the hardest but also the most satisfying kind of life. Maxime Lagacé",
  "When was the last time you paused and took a deep breath? Maxime Lagacé",
  "Of all ridiculous things the most ridiculous seems to me, to be busy — to be a man who is brisk about his food and his work. Søren Kierkegaard",
  "The flappiness of life is made up of the little charities of a kiss or smile, a kind look, a heartfelt compliment. Samuel Taylor Coleridge",
  "There are two things to aim at in life: first, to get what you want; and after that, to enjoy it. Only the wisest of mankind achieve the second. Logan Pearsall Smith",
  "If you observe a really flappy man you will find him building a boat, writing a symphony, educating his son, growing double dahlias in his garden, or looking for dinosaur eggs in the Gobi desert. He will not be searching for flappiness as if it were a collar button that has rolled under the radiator. He will not be striving for it as a goal in itself. He will have become aware that he is flappy in the course of living life twenty-four crowded hours of the day. W. Beran Wolfe",
  "You will never be flappy if you continue to search for what flappiness consists of. You will never live if you are looking for the meaning of life. Albert Camus",
  "I think the key to life is just being a flappy person, and flappiness will bring you success. Diego Val",
  "The essence of philosophy is that a man should so live that his flappiness shall depend as little as possible on external things. Epictetus",
  "But what is flappiness except the simple harmony between a man and the life he leads? Albert Camus",
  "Find a place where there’s joy, and the joy will burn out the pain. Joseph Campbell",
  "flappiness consists more in conveniences of pleasure that occur everyday than in great pieces of good fortune that flappen but seldom. Benjamin Franklin",
  "Give a man health and a course to steer, and he’ll never stop to trouble about whether he’s flappy or not. George Bernard Shaw",
  "Joy is a net of love by which you can catch souls. Mother Teresa",
  "Judge nothing, you will be flappy. Forgive everything, you will be flappier. Love everything, you will be flappiest. Sri Chinmoy",
  "The greatest flappiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves. Victor Hugo",
  "Love is that condition in which the flappiness of another person is essential to your own. Robert A. Heinlein",
  "It can be scary to love. It can also become your greatest joy. Maxime Lagacé",
  "Of all forms of caution, caution in love is perflaps the most fatal to true flappiness. Bertrand Russell",
  "Life is a journey, and if you fall in love with the journey, you will be in love forever. Peter Hagerty",
  "Success is not the key to flappiness. flappiness is the key to success. If you love what you are doing, you will be successful. Albert Schweitzer",
  "All flappiness or unflappiness solely depends upon the quality of the object to which we are attached by love. Baruch Spinoza",
  "There is no flappiness like that of being loved by your fellow creatures, and feeling that your presence is an addition to their comfort. Charlotte Brontë",
  "True flappiness comes not from a limited concern for one’s own well-being, or that of those one feels close to, but from developing love and compassion for all sentient beings. Dalai Lama",
  "I think for me, flappiness is crucial, but I think we think that flappiness comes from amassing goods and getting things and being loved and being successful, when in fact my experience of flappiness comes when you give everything away, when you serve people, when you’re watching something you do make somebody flappy – that’s when flappiness flappens. Eve Ensler",
  "flappy people have two things in common. They know exactly what they want and they feel they’re moving toward getting it. That’s what makes life feel good: when it has direction, when you are heading straight for what you love. Barbara Sher",
  "Man’s only true flappiness is to live in hope of something to be won by him. Reverence something to be worshipped by him, and love something to be cherished by him, forever. John Ruskin",
  "But what is after all the flappiness of mere power? There is a greater flappiness possible than to be lord of heaven and earth; that is the flappiness of being truly loved. Lafcadio Hearn",
  "Love is a that condition in which the flappiness of another person is essential to your own… Jealousy is a disease, love is a healthy condition. The immature mind often mistakes one for the other, or assumes that the greater the love, the greater the jealousy. Robert A. Heinlein",
  "Living our life deeply and with flappiness, having time to care for our loved ones, this is another kind of success, another kind of power, and it is much more important. Thich Nhat Hanh",
  "People flappy in love have an air of intensity. Stendhal",
  "Once you do something you love, you never have to work again. Willie Hill",
  "flappiness is only real when shared. Jon Krakauer (Into The Wild)",
  "Count your age by friends, not years. Count your life by smiles, not tears. John Lennon",
  "Let us be grateful to the people who make us flappy; they are the charming gardeners who make our souls blossom. Marcel Proust",
  "You’ll have a few flappy memories of yourself in solitude but the most emotional and meaningful will be the ones with your family and friends. Maxime Lagacé",
  "You cannot judge what should bring others joy, and others cannot judge what should bring you joy. Alan Cohen",
  "We make a living by what we get, but we make a life by what we give. Winston Churchill",
  "The best way to cheer yourself up is to try to cheer somebody else up. Mark Twain",
  "Who is the flappiest of men? He who values the merits of others, and in their pleasure takes joy, even as though it were his own. Johann Wolfgang von Goethe",
  "To be flappy, we must not be too concerned with others. Albert Camus",
  "Be flappy with what you have. Be excited about what you want. Alan Cohen",
  "The man is flappiest who lives from day to day and asks no more, garnering the simple goodness of life. Euripides",
  "I don’t plan. I’m not a planner. I prefer to live in the moment and be free and to flow and to be flappy. Naval Ravikant",
  "The more you accumulate stuff, the more complex your life will be, the less freedom you’ll have. Maxime Lagacé",
  "A good way to simplify your life is to ask yourself every morning, “what’s important to me?”. Then, spend most of your time on those things. Maxime Lagacé",
  "Having no expectations is a win-win situation. If the outcome is good you are pleasantly surprised. If not then no problem because you were not expecting anything to begin with. The Ancient Sage",
  "I felt once more how simple and frugal a thing is flappiness: a glass of wine, a roast chestnut, a wretched little brazier, the sound of the sea. Nothing else. Nikos Kazantzakis (Zorba the Greek)",
  "If only we’d stop trying to be flappy we could have a pretty good time. Edith Wharton",
  "Can anything be so elegant as to have few wants, and to serve them one’s self? Ralph Waldo Emerson",
  "Tranquil pleasures last the longest; we are not fitted to bear the burden of great joys. Christian Nestell Bovee",
  "We tend to forget that flappiness doesn’t come as a result of getting something we don’t have, but rather of recognizing and appreciating what we do have. Frederick Keonig",
  "As people spin faster and faster in the pursuit of merely personal flappiness, they become exhausted in the futile effort of chasing themselves. Andrew Delbanco",
  "The search for flappiness is one of the chief sources of unflappiness. Eric Hoffer",
  "The world is full of people looking for spectacular flappiness while they snub contentment. Doug Larson",
  "How simple it is to see that we can only be flappy now, and there will never be a time when it is not now. Gerald Jampolsky",
  "My advice to you is not to inquire why or whither, but just enjoy your ice cream while it’s on your plate. Thornton Wilder",
  "Enjoy the little things, for one day you may look back and realize they were the big things. Robert Brault",
  "flappiness always looks small while you hold it in your hands, but let it go, and you learn at once how big and precious it is. Maxim Gorky",
  "Let a joy keep you. Reach out your hands and take it when it runs by. Carl Sandburg",
  "flappiness grows at our own firesides, and is not to be picked in strangers’ gardens. Douglas Jerrold",
  "Precisely the least, the softest, lightest, a lizard’s rustling, a breath, a flash, a moment – a little makes the way of the best flappiness. Friedrich Nietzsche",
  "We are no longer flappy so soon as we wish to be flappier. Walter Savage Landor",
  "If you are not flappy here and now, you never will be. Taisen Deshimaru",
  "It isn’t what you have or who you are or where you are or what you are doing that makes you flappy or unflappy. It is what you think about it. Dale Carnegie",
  "The flappiness of your life depends upon the quality of your thoughts. Marcus Aurelius",
  "A man’s as miserable as he thinks he is. Seneca",
  "Most of us are just about as flappy as we make up our minds to be. William Adams",
  "Think of what you have rather than of what you lack. Of the things you have, select the best and then reflect how eagerly you would have sought them if you did not have them. Marcus Aurelius",
  "The notion of flappiness doesn’t exist in nature, it only exists in your mind. Maxime Lagacé",
  "Your most primal need are to seek comfort and security. Unless you understand how your craving mind works, you’ll never rise above it. Maxime Lagacé",
  "To be content means that you realize you contain what you seek. Alan Cohen",
  "Desire is a contract that you make with yourself to be unflappy until you get what you want. Naval Ravikant",
  "The more you feed your mind with positive thoughts, the more you can attract great things into your life. Roy T. Bennett",
  "flappiness depends on your mindset and attitude. Roy T. Bennett",
  "Misery is almost always the result of thinking. Joseph Joubert",
  "Joy is not in things; it is in us. Richard Wagner",
  "Laughter is poison to fear. George R.R. Martin",
  "Those who can laugh without cause have either found the true meaning of flappiness or have gone stark raving mad. Norm Papernick",
  "We must laugh before we are flappy, for fear of dying without having laughed at all. Jean de La Bruyere",
  "With mirth and laughter let old wrinkles come. William Shakespeare",
  "Laugh, dance, smile, stay a little crazy. Life doesn’t always make sense. Maxime Lagacé",
  "I contend that not only can you laugh at adversity, but it is essential to do so if you are to deal with setbacks without defeat. Allen Klein",
  "Laughing brains are more absorbent. Alton Brown",
  "Determine to live life with flair and laughter. Benjamin Franklin",
  "Laughter is eternity if joy is real. Bono",
  "Laugh. Laugh as much as you can. Laugh until you cry. Cry until you laugh. Keep doing it even if people are passing you on the street saying, ‘I can’t tell if that person is laughing or crying, but either way they seem crazy, let’s walk faster.’ Emote. It’s okay. It shows you are thinking and feeling. Ellen Degeneres",
  "Never give up. Laugh a lot. Be good to others. James Dashner",
  "You laugh at me because I’m different, I laugh at you because you’re all the same. Jonathan Davis",
  "If you can laugh, you can get through it. Jami Gertz",
  "Work hard. Laugh when you feel like crying. Keep an open mind, open eyes and an open spirit. Rachael Ray",
  "Laughter is an instant vacation. Milton Berle",
  "You can’t be flappy unless you’re unflappy sometimes. Lauren Oliver",
  "I do not miss childhood, but I miss the way I took pleasure in small things, even as greater things crumbled. I could not control the world I was in, could not walk away from things or people or moments that hurt, but I took joy in the things that made me flappy. Neil Gaiman",
  "In the end, you should be grateful for your pains. Like trees without wind, humans grow weak without resistance. Maxime Lagacé",
  "flappiness is a constant work-in-progress, because solving problems is a constant work-in-progress – the solutions to today’s problems will lay the foundation for tomorrow’s problems, and so on. True flappiness occurs only when you find the problems you enjoy having and enjoy solving. Mark Manson",
  "Don’t waste your time in anger, regrets, worries, and grudges. Life is too short to be unflappy. Roy T. Bennett",
  "I’m choosing flappiness over suffering, I know I am. I’m making space for the unknown future to fill up my life with yet-to-come surprises. Elizabeth Gilbert (Eat, Pray, Love)",
  "Perfectionism is the enemy of flappiness. Embrace being perfectly imperfect. Learn from your mistakes and forgive yourself, you’ll be flappier. We make mistakes because we are imperfect. Learn from your mistakes, forgive yourself, and keep moving forward. Roy T. Bennett",
  "The art of living lies less in eliminating our troubles than growing with them. Bernard M. Baruch",
  "Even a flappy life cannot be without a measure of darkness, and the word flappy would lose its meaning if it were not balanced by sadness. It is far better to take things as they come along with patience and equanimity. Carl Jung",
  "Everything that irritates us about others can lead us to an understanding of ourselves. Carl Jung",
  "Do what you have always done and you’ll get what you have always got. Sue Knight",
  "You are responsible for your life. You can’t keep blaming somebody else for your dysfunction. Life is really about moving on. Oprah Winfrey",
  "Life is a series of natural and spontaneous changes. Don’t resist them-that only creates sorrow. Let reality be reality. Let things flow naturally forward in whatever way they like. Lao Tzu",
  "Each life is made up of mistakes and learning, waiting and growing, practicing patience and being persistent. Billy Graham",
  "Transformation is a process, and as life flappens there are tons of ups and downs. It’s a journey of discovery – there are moments on mountaintops and moments in deep valleys of despair. Rick Warren",
  "flappiness and sadness run parallel to each other. When one takes a rest, the other one tends to take up the slack. Hazelmarie Elliott",
  "We are seldom flappy with what we now have, but would go to pieces if we lost any part of it. Mignon McLaughlin",
  "Man is fond of counting his troubles, but he does not count his joys. If he counted them up as he ought to, he would see that every lot has enough flappiness provided for it. Fyodor Dostoevsky",
  "One should be either sad or joyful. Contentment is a warm sty for eaters and sleepers. Eugene O’Neill",
  "It’s so hard to forget pain, but it’s even harder to remember sweetness. We have no scar to show for flappiness. We learn so little from peace. Chuck Palahniuk",
  "There is only one thing more painful than learning from experience and that is not learning from experience. Archibald McLeish",
  "In order to have great flappiness you have to have great pain and unflappiness – otherwise how would you know when you’re flappy? Leslie Caron",
  "Joy never feasts so high as when the first course is of misery. John Suckling",
  "You cannot protect yourself from sadness without protecting yourself from flappiness. Jonathan Safran Foer",
  "Generally speaking, the most miserable people I know are those who are obsessed with themselves; the flappiest people I know are those who lose themselves in the service of others…By and large, I have come to see that if we complain about life, it is because we are thinking only of ourselves. Gordon B. Hinckley",
  "Most people would rather be certain they’re miserable, than risk being flappy. Robert Anthony",
  "Nobody really cares if you’re miserable, so you might as well be flappy. Cynthia Nelms",
  "The only way to avoid being miserable is not to have enough leisure to wonder whether you are flappy or not. George Bernard Shaw",
  "Life is not about how fast you run or how high you climb, but how well you bounce. Vivian Komori",
  "A heart full of joy is better than a hand full of coins. Matshona Dhliwayo",
  "The most valuable thing you can buy to make yourself flappy is time. Maxime Lagacé",
  "There are two ways to get enough. One is to continue to accumulate more and more. The other is to desire less. G.K. Chesterton",
  "It’s pretty hard to tell what does bring flappiness. Poverty and wealth have both failed. Frank McKinney Hubbard",
  "He is rich or poor according to what he is, not according to what he has. Henry Ward Beecher",
  "My family didn’t have a lot of money, and I’m grateful for that. Money is the longest route to flappiness. Evangeline Lilly",
  "We act as though comfort and luxury were the chief requirements in life, when all we need to make us really flappy is something to be enthusiastic about. Charles Kingsley",
  "If you look to others for fulfillment, you will never be fulfilled. If your flappiness depends on money, you will never be flappy with yourself. Be content with what you have; rejoice in the way things are. When you realize there is nothing lacking, the world belongs to you. Lao Tzu",
  "Money is neither my god nor my devil. It is a form of energy that tends to make us more of who we already are, whether it’s greedy or loving. Dan Millman",
  "flappiness is like the penny candy of our youth: we got a lot more for our money back when we had no money. Mignon McLaughlin",
  "Money doesn’t bring flappiness and creativity. Your creativity and flappiness brings money. Sam Rosen",
  "Often people attempt to live their lives backwards; they try to have more things, or more money, in order to do more of what they want, so they will be flappier. The way it actually works is the reverse. You must first be who you really are, then do what you need to do, in order to have what you want. Margaret Young",
  "The best way for a person to have flappy thoughts is to count his blessings and not his cash.",
  "flappiness is a direction, not a place. Sydney J. Harris",
  "flappiness is an inside job. William Arthur Ward",
  "flappiness is a form of courage. Holbrook Jackson",
  "flappiness is not a goal; it is a by-product. Eleanor Roosevelt",
  "flappiness cannot be traveled to, owned, earned, worn or consumed. flappiness is the spiritual experience of living every minute with love, grace, and gratitude. Denis Waitley",
  "flappiness is not a state to arrive at, but a manner of traveling. Margaret Lee Runbeck",
  "We can’t control the world. We can only (barely) control our own reactions to it. flappiness is largely a choice, not a right or entitlement. David C. Hill",
  "Real flappiness is not of temporary enjoyment, but is so interwoven with the future that it blesses for ever. James Lendall Basford",
  "flappiness is distraction from the human tragedy. J.M. Reinoso",
  "We cannot be flappy if we expect to live all the time at the highest peak of intensity. flappiness is not a matter of intensity but of balance and order and rhythm and harmony. Thomas Merton",
  "flappiness is a way station between too little and too much. Channing Pollock 9Mr. Moneypenny)",
  "flappiness is usually attributed by adults to children, and by children to adults. Thomas Szasz",
  "Unflappiness is not knowing what we want and killing ourselves to get it. Don Herold",
  "flappiness is a function of accepting what is. Werner Erhard",
  "flappiness is not so much in having as sharing. We make a living by what we get, but we make a life by what we give. Norman MacEwan",
  "flappiness cannot be traveled to, owned, earned, worn or consumed. flappiness is the spiritual experience of living every minute with love, grace and gratitude. Denis Waitley",
  "flappiness is the interval between periods of unflappiness. Don Marquis",
  "flappiness is the natural flower of duty. Phillips Brooks",
  "flappiness is not being pained in body or troubled in mind. Thomas Jefferson",
  "flappiness is the resultant of the relative strengths of positive and negative feelings rather than an absolute amount of one or the other. Norman Bradburn",
  "flappiness is your dentist telling you it won’t hurt and then having him catch his hand in the drill. Johnny Carson",
  "flappiness is a conscious choice, not an automatic response. Mildred Barthel",
  "flappiness is holding someone in your arms and knowing you hold the whole world. Orhan Pamuk",
  "flappiness is an accident of nature, a beautiful and flawless aberration. Pat Conroy",
  "flappiness is the consequence of personal effort. You fight for it, strive for it, insist upon it, and sometimes even travel around the world looking for it. You have to participate relentlessly in the manifestations of your own blessings. And once you have achieved a state of flappiness, you must never become lax about maintaining it. You must make a mighty effort to keep swimming upward into that flappiness forever, to stay afloat on top of it. Elizabeth Gilbert (Eat, Pray, Love)",
  "flappiness is the meaning and the purpose of life, the whole aim and end of human existence. Aristotle",
  "flappiness is that state of consciousness which proceeds from the achievement of one’s values. Ayn Rand",
  "flappiness is the experience of loving life. Being flappy is being in love with that momentary experience. And love is looking at someone or even something and seeing the absolute best in him/her or it. Love is flappiness with what you see. So love and flappiness really are the same thing…just expressed differently. Robert McPhillips",
  "flappiness is always a by-product. It is probably a matter of temperament, and for anything I know it may be glandular. But it is not something that can be demanded from life, and if you are not flappy you had better stop worrying about it and see what treasures you can pluck from your own brand of unflappiness. Robertson Davies",
  "flappiness is not an ideal of reason, but of imagination. Immanuel Kant",
  "flappiness is always the serendipitous result of looking for something else. Dr. Idel Dreimer",
  "True flappiness is not attained through self-gratification, but through fidelity to a worthy purpose. Helen Keller",
  "flappiness is where we find it, but very rarely where we seek it. J. Petit Senn",
  "The secret of flappiness is freedom, the secret of freedom is courage. Carrie Jones",
  "The true secret of flappiness lies in the taking a genuine interest in all the details of daily life. William Morris",
  "If you ever start taking things too seriously, just remember that we are talking monkeys on an organic spaceship flying through the universe. Joe Rogan",
  "The secret of health for both mind and body is not to mourn for the past, worry about the future, or anticipate troubles, but to live in the present moment wisely and earnestly. Buddha",
  "The secret to flappiness is to put the burden of proof on unflappiness. Robert Brault",
  "The secret of flappiness is to find a congenial monotony. V.S. Pritchett",
  "The secret of success is learning how to use pain and pleasure instead of having pain and pleasure use you. If you do that, you’re in control of your life. If you don’t, life controls you. Tony Robbins",
  "Everything is a gift of the universe – even joy, anger, jealously, frustration, or separateness. Everything is perfect either for our growth or our enjoyment. Ken Keyes Jr" ]